name: stagexl_rockdot
version: 0.0.1
description: StageXL port of Rockdot framework, based on Spring framework for StageXL.
dependencies:
  stagexl_spring:
    git: https://github.com/blockforest/stagexl-spring
